### PR TITLE
A number of minor improvements

### PR DESCRIPTION
**Pull request by rpgoldman**
Here are a number of small modifications to CL-CUDD to make it load smoothly.

I fixed the issue with PI by shadowing it in the package for the API.  I also refined the foreign library loader to handle Mac as well as Linux.

I think it would be possible to have ASDF automatically run SWIG to generate the cuddapi.lisp file, but haven't done that yet.

LMK if you are no longer interested in this library, and I will stop bothering you.

### CODE REVIEW

**Comment by Neronus** [comment]
Hi,

Thank you a lot for taking an interest :)
I'll go over your fixes this weekend, review them, and incorporate them.

I'm sorry for not having answered before, there really is no excuse.

Out of curiosity: are you using it, and if yes, what for?

Thank you,

Christian

**Comment by rpgoldman** [comment]
To be honest, I am not using CL-CUDD at the moment.  I was using it to
try to replicate the CEGAR (counterexample guided abstraction
refinement) algorithm by Clarke, et al.

I tried CL-CUDD, but the need to dereference the CL data structures to
get at the embedded BDDs made the code too burdensome, and I ended up
doing this project using Fabio Somenzi's PerlDD perl interface to CUDD
instead.

I believe that the right thing (I might be able to contribute some
cycles to this) would be to modify CL-CUDD to use the CFFI methods to
translate foreign values in order to automatically access the embedded
BDD pointers in the CL objects, instead of requiring the programmer to
do this.

I couldn't afford to do this myself, since I am not enough of an expert
with CFFI, and it wasn't an appropriate use of the time and funds for my
CEGAR project.  But if you are interested in doing something along these
lines, it would be a good way for me to learn more about CFFI.

**Comment by Neronus** [comment]
Many thanks, it's perfect!

**Comment by Neronus** [comment]
I'd like to know what you mean with

> I tried CL-CUDD, but the need to dereference the CL data structures to
> get at the embedded BDDs made the code too burdensome, and I ended up
> doing this project using Fabio Somenzi's PerlDD perl interface to CUDD
> instead.

Espcecially what you mean by "dereference", i.e., do you mean the reference counting inherent in CUDD,
or something else?

If you want to work with the raw pointers, then you can use the cuddapi package, which is the thin wrapper around the C interface. No garbage collection, of course.

**Comment by rpgoldman** [comment]
What I meant was that I wanted to work with the `BDD-NODE` objects, but it seemed like I often had to write code where I would be invoking `(node-pointer node)` and then passing the resulting raw C pointer to one of the functions through something in cuddapi.lisp.  Maybe I was misunderstanding and this wrapping and unwrapping does happen automatically; I couldn't figure it out.

It looked to me like we should be able to define CFFI translation functions that would take a `BDD-NODE` (or `ADD-NODE`, etc.) object and, when passing it to a cuddapi function, would automagically pull out the `NODE-POINTER` value.  Similarly, the cuddapi functions could return something that would be automagically wrapped in a `BDD-NODE`.

**Pull request merged**
